-- POSTGRESQL DATA MODEL FOR THIS APP

-- TYPES

CREATE TYPE TASKS_STATUS_TYPE AS ENUM('PENDING','COMPLETED');
CREATE TYPE INVITATION_STATUS_TYPE AS ENUM('INVITED','JOINED','REJECTED');
CREATE TYPE USERS_ACCOUNT_STATUS AS ENUM('ACTIVE','INACTIVE');

-- TABLES 

CREATE TABLE USERS(
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE,
    BIO VARCHAR(180),
    HASHED_PASSWORD TEXT NOT NULL,
    STATUS USERS_ACCOUNT_STATUS NOT NULL DEFAULT 'ACTIVE',
    PHONE VARCHAR(16),
    LINKED_IN_URL TEXT,
    GITHUB_URL TEXT,
    AVATAR_URL TEXT NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);  

CREATE TABLE ROLES(
    ID SERIAL PRIMARY KEY,
    TITLE TEXT NOT NULL UNIQUE,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO ROLES(TITLE)
VALUES('OWNER'),('MANAGER'),('MEMBER');

CREATE TABLE PROJECTS(
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    CREATED_BY INTEGER REFERENCES USERS(ID) ON DELETE RESTRICT,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE PROJECT_MEMBERS(
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER NOT NULL REFERENCES USERS(ID) ON DELETE RESTRICT, 
    PROJECT_ID INTEGER NOT NULL REFERENCES PROJECTS(ID) ON DELETE RESTRICT,
    ROLE_ID INTEGER NOT NULL REFERENCES ROLES(ID) ON DELETE RESTRICT,
    ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(USER_ID,PROJECT_ID)
);

CREATE TABLE TASKS(
    ID SERIAL PRIMARY KEY,
    TITLE TEXT NOT NULL,
    STATUS TASKS_STATUS_TYPE NOT NULL,
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    DEADLINE TIMESTAMPTZ,

    PROJECT_ID INTEGER NOT NULL REFERENCES PROJECTS(ID) ON DELETE RESTRICT,
    ASSIGNED_BY INTEGER NOT NULL REFERENCES USERS(ID) ON DELETE RESTRICT,
    ASSIGNED_TO INTEGER NOT NULL REFERENCES USERS(ID) ON DELETE RESTRICT,

    UNIQUE(TITLE,PROJECT_ID)
);

CREATE TABLE INVITATIONS(
    ID SERIAL PRIMARY KEY,
    STATUS INVITATION_STATUS_TYPE NOT NULL DEFAULT 'INVITED',
    MESSAGE TEXT,
    INVITED_AT TIMESTAMPTZ DEFAULT NOW(),

    ROLE_ID INTEGER NOT NULL REFERENCES ROLES(ID) ON DELETE RESTRICT,
    PROJECT_ID INTEGER NOT NULL REFERENCES PROJECTS(ID) ON DELETE RESTRICT,
    INVITED_BY INTEGER NOT NULL REFERENCES USERS(ID) ON DELETE RESTRICT,
    INVITED_USER_ID INTEGER NOT NULL REFERENCES USERS(ID) ON DELETE RESTRICT
);

-- Indexes : To speeden reading data

CREATE INDEX idx_projects_created_by
ON PROJECTS(CREATED_BY);

CREATE UNIQUE INDEX idx_project_unique_name
ON PROJECTS(NAME);

CREATE INDEX idx_project_members_user_id
ON PROJECT_MEMBERS(USER_ID);

CREATE INDEX idx_project_members_role_id
ON PROJECT_MEMBERS(ROLE_ID);

CREATE UNIQUE INDEX one_owner_only_per_project
ON PROJECT_MEMBERS(PROJECT_ID)
WHERE ROLE_ID = 1;

CREATE INDEX idx_tasks_assigned_to
ON TASKS(ASSIGNED_TO);

CREATE INDEX idx_tasks_assigned_by
ON TASKS(ASSIGNED_BY);

CREATE INDEX idx_tasks_project_id
ON TASKS(PROJECT_ID);

CREATE INDEX idx_invitations_project_id
ON INVITATIONS(PROJECT_ID);

CREATE INDEX idx_invitations_invited_by
ON INVITATIONS(INVITED_BY);

CREATE INDEX idx_invitations_invited_user_id
ON INVITATIONS(INVITED_USER_ID);

CREATE INDEX idx_invitations_invited_user_role_id
ON INVITATIONS(ROLE_ID);

CREATE UNIQUE INDEX idx_unique_pending_invitation
ON invitations(project_id, invited_user_id)
WHERE status='INVITED';